name: Publish Release Nuget Package

on:
  push:
    branches: 
      - master

jobs:
  workflow-calling:
    uses: tiagomartimiano/github-nuget-prerelease-release-workflow/.github/workflows/dotnet-nuget-release.yml@v1.0.0
    secrets: inherit